### PR TITLE
Change 5.03 to 4.01 response in case of replay

### PR DESCRIPTION
**Pull request by fpalombini**
on server side. Also, error is unprotected (as all other OSCORE errors)
see #191

### CODE REVIEW

**Comment by emanjon** [comment]
RFC7252 specifies that 5.03 uses Max-Age. Now when we use 4.01, I think Max-Age should (need to) be removed.

**Comment by fpalombini** [comment]
@emanjon This was an oversight on my part. One question though: what was the reason to say: 

> A server MAY set a Class U Max-Age option with value zero to Observe responses (see Section 5.6.1 of {{RFC7252}}) which is then processed according to {{outer-options}}.

Why do we specify for Observe responses? A server MAY set an outer Max-Age=0 with all responses (as an indication to the proxy not to cache), also for error responses (not protected with Object-Security) to an OSCORE request.

**Comment by emanjon** [comment]
The reason why we talked about Max-Age is to avoid caching by a OSCORE unanaware proxy. This was not needed for 2.04. if we change to only 2.04 we should remove this completely.

**Comment by fpalombini** [comment]
Ok, because 2.04 is non cacheable. but error responses are cacheable, so following the same logic we should say that the server MAY set max-age = 0 for error responses, no?

**Comment by emanjon** [comment]
Yes, that makes sense.

**Pull request merged**
