### PR TITLE
Replace Sender IV and Recipient IV with a common Context IV

### PR DESCRIPTION
**Pull request by emanjon**
After reviewing the newly added section on "Nonce generation examples", reviewing the multicast draft, and thinking about ways to reduce the memory usage of OSCOAP I have come to the conclusion that I think the Sender IV and Recipient IV should be replaced with a common Context IV (in the Common Context) (I.e. a Fixed-Common field according to RFC5116). As each endpoint uses a unique key for encryption, a Fixed-Distinct field (RFC5116) is not necessary. 

+ This significantly reduces memory usage or processing (depending on the implementation) especially in the case of multicast or an endpoint with many security contexts. 

+ This simplifies the specification

+ This simplifies the implementation

+ This makes it easier to analyse the security.

The Context IV (Fixed field according to RFC5116) are used to protect against pre-computation and time-memory tradeoff attacks. A Common IV in the common context would fulfil this purpose.

### CODE REVIEW

**Comment by emanjon** [comment]
Implemented in recent commits

**Comment by jimsch** [comment]
Before doing this did you do an analysis on any problems with doing reflection attacks?

**Comment by gselander** [comment]
Since all sent messages are encrypted, integrity protected and monotonically numbered by the sender, and since there are different keys for each sender I didn't understand how the attack would look like. Could you say more about the attack you had in mind?

**Comment by jimsch** [comment]
I am worried about moving the same optimization to the group side.  In that case there is a common key.

**Comment by gselander** [comment]
Even if there is a shared master key, the keys used in the different messages (multicast message, response from listener1, response from listener2,  etc.) would be different.

**Comment by jimsch** [comment]
I do not believe that is a correct statement.  If it is then my understanding of the oscoap group document is completely wrong.

**Pull request closed without merging**
